# Generated by Django 6.0.3 on 2026-03-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='category',
            field=models.CharField(default='All', max_length=50),
        ),
        migrations.AddField(
            model_name='scheme',
            name='income_limit',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='scheme',
            name='max_age',
            field=models.IntegerField(default=65),
        ),
        migrations.AddField(
            model_name='scheme',
            name='min_age',
            field=models.IntegerField(default=18),
        ),
    ]
