# Generated by Django 6.0.3 on 2026-03-26 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_scheme_category_scheme_income_limit_scheme_max_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='applicationrequest',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmers.scheme'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='apply_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='documents_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationrequest',
            name='income',
            field=models.IntegerField(),
        ),
    ]
